version: '3.8'

services:
  globalanalytics-api:
    build:
      context: ..
      dockerfile: GlobalAnalytics.Deployment/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=LAPTOP-0BPA3HAG\GAMIK;Database=GlobalAnalytics;User=sa;Password=Kittu@2202@;
    depends_on:
      - sql-server

  sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: LAPTOP-0BPA3HAG\GAMIK
    environment:
      SA_PASSWORD: "Kittu@2202@"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
