pipeline {
    agent any

    environment {
        DOTNET_ROOT = "/usr/share/dotnet"
        PROJECT_PATH = "GlobalAnalytics.API"
        IMAGE_NAME = "globalanalytics-api"
    }

    tools {
        dotnet "dotnet8"  
    }

    stages {
        stage('Clean') {
            steps {
                sh 'dotnet clean'
            }
        }

        stage('Restore') {
            steps {
                sh 'dotnet restore'
            }
        }

        stage('Build') {
            steps {
                sh 'dotnet build --configuration Release --no-restore'
            }
        }

        stage('Test') {
            steps {
                sh 'dotnet test --no-build --verbosity normal'
            }
        }

        stage('Publish') {
            steps {
                sh "dotnet publish ${PROJECT_PATH} -c Release -o ./publish"
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}:latest", "-f ${PROJECT_PATH}/Dockerfile ./")
                }
            }
        }

        stage('Docker Run') {
            steps {
                sh "docker-compose -f docker-compose.yml up -d"
            }
        }
    }

    post {
        always {
            echo 'Pipeline finished.'
        }
        failure {
            echo 'Pipeline failed. Check logs.'
        }
    }
}
